-- CreateTable
CREATE TABLE "specialty_analytics" (
    "id" SERIAL NOT NULL,
    "specialty" TEXT NOT NULL,
    "division" TEXT NOT NULL,
    "success_count" INTEGER NOT NULL,
    "success_count_history" JSONB NOT NULL,
    "success_count_diff" INTEGER NOT NULL,
    "base_score" DOUBLE PRECISION,
    "base_score_history" JSONB NOT NULL,
    "base_score_diff" DOUBLE PRECISION,
    "avg_score" DOUBLE PRECISION,
    "avg_score_history" JSONB NOT NULL,
    "avg_score_diff" DOUBLE PRECISION,
    "top_5_destination_regions" JSONB NOT NULL,
    "top_5_competitive_regions" JSONB NOT NULL,
    "national_points_range" DOUBLE PRECISION,
    "national_points_range_history" JSONB NOT NULL,
    "national_points_range_diff" DOUBLE PRECISION,
    "special_category_rate" DOUBLE PRECISION,
    "special_category_rate_history" JSONB NOT NULL,
    "special_category_rate_diff" DOUBLE PRECISION,
    "active_regions_rate" DOUBLE PRECISION,
    "active_regions_rate_history" JSONB NOT NULL,
    "active_regions_rate_diff" DOUBLE PRECISION,
    "leaving_count" INTEGER NOT NULL,
    "leaving_count_history" JSONB NOT NULL,
    "leaving_count_diff" INTEGER NOT NULL,
    "top_5_targeting_1st" JSONB NOT NULL,
    "avg_score_applicants" DOUBLE PRECISION,
    "avg_score_applicants_history" JSONB NOT NULL,
    "avg_score_applicants_diff" DOUBLE PRECISION,
    "average_preference_count" DOUBLE PRECISION,
    "average_preference_count_history" JSONB NOT NULL,
    "average_preference_count_diff" DOUBLE PRECISION,
    "points_entrance_gap" DOUBLE PRECISION,
    "points_entrance_gap_history" JSONB NOT NULL,
    "points_entrance_gap_diff" DOUBLE PRECISION,
    "odds_of_transfer" DOUBLE PRECISION,
    "odds_of_transfer_history" JSONB NOT NULL,
    "odds_of_transfer_diff" DOUBLE PRECISION,
    "waiting_list_absolute" INTEGER NOT NULL,
    "waiting_list_absolute_history" JSONB NOT NULL,
    "waiting_list_absolute_diff" INTEGER NOT NULL,

    CONSTRAINT "specialty_analytics_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "specialty_analytics_specialty_division_key" ON "specialty_analytics"("specialty", "division");
